name: CMake Build check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..
      
    - name: Build project
      working-directory: ./build
      run: cmake --build . --config Release
